name: Deploy Demo Page

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    uses: marcintk/ha-card-shared/.github/workflows/shared-deploy-demo-page.yml@v1.0.0
    permissions:
      contents: read
      pages: write
      id-token: write
